### ISSUE TITLE
Exception - Mobile-ID error: 104

### ISSUE THREAD

**Issue by dsbellcom** [mangus/mobile_id#4]
I always get an error "Exception - Mobile-ID error: 104" when trying to login. What should I check or fix? Please, let me know, if this module is outdated and no longer working.
Best wishes.

**Comment by mangus** [comment]
The plugin hasn't been updated for more than 4 years, I don't know if it works anymore.
Looks like https://moodle.hitsa.ee is still using it.

From http://sk-eid.github.io/dds-documentation/api/api_docs/#soap-error-messages
error code 104 means: "Client is not authorized to access service".
And codes 100-199 mean "errors caused by user (Application Provider) of the service".
So looks more like a problem of Your setup/server than the plugin.

**Comment by dsbellcom** [comment]
Thank you for the answer! I will report my results later.

**Comment by dsbellcom** [comment]
Works with these changes:
On auth.php lines 52-54 params should be in this order: CountryCode(string), PhoneNo(string), Language(string), ServiceName(string), MessageToDisplay(string), SPChallenge(string), MessagingMode(string), AsyncConfiguration(int), ReturnCertData(boolean), ReturnRevocationData(boolean).
More info:
http://sk-eid.github.io/dds-documentation/api/api_docs/
